language: java
jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

before_script:
  - echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc

script:
  - mvn package -DskipTests
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - export DEB_FILE=$(ls target/*.deb)

deploy:
  provider: releases
  api_key: "${GITHUB_TOKEN}"
  file: "${DEB_FILE}"
  skip_cleanup: true
  on:
    tags: true
